### ISSUE TITLE
use of illumos project phoenix logo

### ISSUE THREAD

**Issue by jclulow** [flock-lab/flock#470]
Hi folks!

I wanted to point out that you seem to be using the logo for the [illumos project](https://github.com/illumos) for your project.  You can see it here, on the organisation page:

![flocklab](https://user-images.githubusercontent.com/304070/201759452-92bfd6ef-afce-4b86-b7f2-5493375caff7.png)

And here again in the repository README:

![flreadme](https://user-images.githubusercontent.com/304070/201759606-362a492f-3172-4469-b528-4a96d011c614.png)

---

As far as I can tell, though this project is interesting it is not an illumos-related project.  The terms for using our logo are [on our site](https://illumos.org/docs/about/logo/).

Can you either clarify how this is illumos-related, so that we can allow the use, or select another logo for your GitHub organisation and your project?

Thanks!

**Comment by gangliao** [comment]
Hi Joshua,

I remember finding this image on a free site that clearly said it‘s free to
use. It provides a series of similar images (same shape in different
poses). Anyway, if it's your original, I'm sorry, I'll delete it tonight.

Best,
Gang

**Comment by jclulow** [comment]
Thanks so much for the quick response!  If you have a pointer to the free site, let me know and I'll follow up with them too.

**Comment by gangliao** [comment]
I changed my macbook recently but probably from here:

- https://www.cleanpng.com/free/sun-microsystems.html

**Comment by pfmooney** [comment]
One remaining bit of cleanup: `flock2.png` is still present `gh-pages` branch (and thus the published flock-lab.github.io site)

Thanks for being so responsive.

**Comment by gangliao** [comment]
Done. Thanks
